### PR TITLE
Added IProgress and CancellationToken for SourcesViewModel LoadDataAsync

### PR DESCRIPTION
**Pull request by Krnlsoft**
Hi, here the PR related to #7 

Please let me know If I understood correctly your requirements.

Thanks!

### CODE REVIEW

**Comment by ahmed-abdelrazek** [comment]
good job so far but the app wouldn't compile if you left it like this
you need to update RefreshSources() in SourcesViewModel.cs and ViewModel.LoadDataAsync().FireAndGet(); in SourcesViewPage.xaml.cs check for reference https://github.com/ahmedflix25/MyRSSFeeds/commit/0aec79be51e631947a0565ead8709a874b2c24ab

**Comment by Krnlsoft** [comment]
Yeah I'm sorry, but something messed up in my dev environment, I'll get back to you

**Comment by ahmed-abdelrazek** [comment]
i think you are using vscode that a UWP app you need the full visual studio 2019 to be able to compile it

**Comment by Krnlsoft** [comment]
Ok I tested and compiled the app correctly, but In my opinion reporting the progress when adding source on the list is useless, since the operation is immediate, It would be better to report the progress after checking if the source is working.
I've added the progress bar on the source list (not pulled, since I don't know if you want this change or not) and made some tests.
What do you think about it?

**Comment by ahmed-abdelrazek** [comment]
there is a separate code that check each item in the list to see if it works or not with with it's own progress because it may take several seconds depending on the source or/and user internet connection

image

your list might load in a second other may take longer like myself and a visual representation is nice also i have another plan for it

thank you for the pull request that helped a lot

**Comment by Krnlsoft** [comment]
Ok Thanks! 
Please consider adding "hacktoberfest" topic to the repository if you wish to participate.

**Comment by Krnlsoft** [comment]
There is a typo error in the topic it's "hacktoberfest" not "hecktoberfest" xD

**Comment by ahmed-abdelrazek** [comment]
how is that got to github auto complete

**Pull request merged**
